business:
  name: "Sample Restaurant"
  type: "restaurant"
  description: "Full-service restaurant with dine-in and takeout"

database:
  url: "sqlite:///restaurant_business.db"
  echo: false

agents:
  accounting:
    enabled: true
    check_interval: 300  # 5 minutes
    anomaly_threshold: 0.25  # 25% variance triggers alert
    alert_thresholds:
      cash_low: 2000  # Alert when cash below $2000
      receivables_overdue: 30  # Alert for receivables overdue by 30+ days
      payables_overdue: 7  # Alert for payables overdue by 7+ days

  inventory:
    enabled: true
    check_interval: 600  # 10 minutes
    low_stock_multiplier: 1.3  # Reorder when stock < reorder_point * multiplier
    reorder_lead_time: 3  # Days
    consumption_analysis_days: 30

  hr:
    enabled: true
    check_interval: 3600  # 1 hour
    overtime_threshold: 8  # Hours per day before overtime
    max_labor_cost_percentage: 0.32  # 32% of revenue
    scheduling_buffer_hours: 2

simulation:
  enabled: true
  mode: "real_time"  # "historical" or "real_time" or "off"
  simulation_interval: 60  # seconds between simulation cycles
  historical_days: 90  # days of historical data to generate
  business_profile:
    avg_daily_revenue: 2800
    revenue_variance: 0.25
    avg_transaction_size: 48
    seasonal_factors:
      1: 0.85  # January
      2: 0.85  # February  
      3: 0.92  # March
      4: 1.05  # April
      5: 1.15  # May
      6: 1.25  # June
      7: 1.35  # July
      8: 1.25  # August
      9: 1.05  # September
      10: 1.05  # October
      11: 1.15  # November
      12: 1.45  # December
    customer_patterns:
      monday: 0.7
      tuesday: 0.8
      wednesday: 0.9
      thursday: 1.0
      friday: 1.35
      saturday: 1.45
      sunday: 1.15

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/restaurant.log"

api:
  enabled: true
  host: "0.0.0.0"
  port: 8000

dashboard:
  enabled: true
  host: "0.0.0.0"
  port: 8501
  auto_refresh_seconds: 30

anthropic:
  model: "claude-3-sonnet-20240229"
  max_tokens: 1000
  temperature: 0.1